---
title: "Stat 151A Final Project EDA"
author: "Andre Sha"
date: "12/9/2020"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(usmap)
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(reshape2)
library(corrplot)
library(car) #VIF
library(gridExtra)
library(cowplot)
library(forecast)
library(dummies)
```

# Data Discovery


```{r}
# Read all datasets
cancer <- read.csv("Data/cancer_reg.csv")
fips_codes <- read.csv("Data/FIPS_codes.csv")
state_abbr <- read.csv("Data/State_Abbreviation_Mapping.csv") 
regions <- read.csv("Data/regions.csv")

```

```{r}
# Cleaned N/A columns
cancer <- subset(cancer, select=-c(PctSomeCol18_24, PctEmployed16_Over, 
                                   PctPrivateCoverageAlone, binnedInc)) 

# Clean coding error, applied log-transformation of PctBachDeg25_Over after plot inspection. 

cancer[cancer$MedianAge > 100,]$MedianAge = 40.8
cancer[cancer$AvgHouseholdSize < 1,]$AvgHouseholdSize = 1
cancer[,"PctBachDeg25_Over"] <- cancer[,"PctBachDeg25_Over"]

```

```{r}
#Joining Datasets, columns w/ Geographic features. 

County <- sub(",.*$", "", cancer$Geography)
State <- sub("^.*,\\s*", "", cancer$Geography)

empty_subs = c(" County", " Parish", " City and Borough", 
               " Municipality", " Borough", " Census Area")
for (sub_string in empty_subs) {
  County <- sub(sub_string, "", County) 
}

County <- sub("city", "City", County) 
County <- sub("St ", "St. ", County) 

cancer$County<- County
cancer$State <- State
cancer <- subset(cancer, select = -c(Geography)) # Redundant
cancer<- cancer %>% 
  rename(
    state = State
    )

fips_codes$County <- sub("St ", "St. ", fips_codes$County) 
fips <- merge(fips_codes, state_abbr[, c('State', 'Postal.Abbreviation')], 
      by.x='State', by.y='Postal.Abbreviation', all.x=TRUE)
fips <- fips %>% 
  rename(
    State.Abbreviation = State,
    state = State.y
    )
cancer <- left_join(cancer, fips, by=c('County', 'state'))
cancer <- cancer %>% 
  rename(
    fips = FIPS
    )

df <- left_join(cancer, regions, by=c('state'))
df <- subset(df, select = -c(State.Code, State.Abbreviation) )

```


```{r}
#Plot Target Rate by County
plot_usmap(data = df, values = "TARGET_deathRate") + 
 scale_fill_continuous(low = "white", high = "red",
                name = "Death Rate", label = scales::comma) + 
  theme(legend.position = "right")
```

```{r}
# Plot Target Rate by State
state_grouped <- df %>%
	group_by(state) %>%
	summarise(
	  TARGET_deathRate = mean(TARGET_deathRate),
	  PctPrivateCoverage = mean(PctPrivateCoverage),
	  BirthRate = mean(BirthRate)
	  )

plot_usmap(data = state_grouped, values = "TARGET_deathRate") + 
  scale_fill_continuous(low = "white", high = "red",
                name = "Death Rate", label = scales::comma) + 
  theme(legend.position = "right")
```
```{r}
# Plot PctWhite Rate by State
plot_usmap(data = state_grouped, values = "BirthRate") + 
 scale_fill_continuous(low = "white", high = "blue",
                name = "Birth Rate", label = scales::comma) + 
  theme(legend.position = "right")
```

```{r}
# Plot PctPrivateCoverage Rate by State
plot_usmap(data = state_grouped, values = "PctPrivateCoverage") + 
  scale_fill_continuous(low = "white", high = "green",
                name = "Private Coverage", label = scales::comma) + 
  theme(legend.position = "right")
```

# EDA 
```{r}
# Create correlation matrix for Non-geographic variables and create a correlation plot. 
df2 <- df[,c(1:29)]

cor(df2)

p.mat <- cor.mtest(df2)$p

corrplot(cor(df2), type = "upper", order = "hclust", tl.pos = "td", tl.cex = 0.5, method = "color", 
         p.mat = p.mat, sig.level = 0.1, insig = "blank")
```

```{r}
# Variance-inflation factor to account for multicollinear variables and remove said features.
full_model <- lm(TARGET_deathRate ~., data = df2)
vif <-car::vif(full_model)

remove_features <- vif[vif > 10]
remove_features



df <- df[, !names(df) %in% names(remove_features)]

# One-Hot Encode state names 
df_state_ohe <- dummy.data.frame(df, names=c("state"), sep="_")

```




